#############################################################################
# Makefile for building: myapp.app/Contents/MacOS/myapp
# Generated by qmake (3.1) (Qt 5.9.7)
# Project:  MineSweeper.pro
# Template: app
# Command: /opt/homebrew/bin/qmake -o Makefile MineSweeper.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -Wno-deprecated-copy -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../opt/anaconda3/include/qt -I../opt/anaconda3/include/qt/QtWidgets -I../opt/anaconda3/include/qt/QtGui -I../opt/anaconda3/include/qt/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/AGL.framework/Headers -I../opt/anaconda3/mkspecs/macx-clang
QMAKE         = /opt/homebrew/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/homebrew/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/homebrew/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = myapp1.0.0
DISTDIR = /Users/taejunha/3307assignment1/.tmp/myapp1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/taejunha/opt/anaconda3/lib
LIBS          = $(SUBLIBS) -L/Users/taejunha/opt/anaconda3/lib -lQt5Widgets -framework DiskArbitration -framework IOKit -lQt5Gui -lQt5Core -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		GameBoard.cpp \
		MainWindow.cpp \
		CellButton.cpp qrc_images.cpp \
		moc_CellButton.cpp \
		moc_GameBoard.cpp \
		moc_MainWindow.cpp
OBJECTS       = main.o \
		GameBoard.o \
		MainWindow.o \
		CellButton.o \
		qrc_images.o \
		moc_CellButton.o \
		moc_GameBoard.o \
		moc_MainWindow.o
DIST          = ../opt/anaconda3/mkspecs/features/spec_pre.prf \
		../opt/anaconda3/mkspecs/qdevice.pri \
		../opt/anaconda3/mkspecs/features/device_config.prf \
		../opt/anaconda3/mkspecs/common/unix.conf \
		../opt/anaconda3/mkspecs/common/mac.conf \
		../opt/anaconda3/mkspecs/common/macx.conf \
		../opt/anaconda3/mkspecs/common/sanitize.conf \
		../opt/anaconda3/mkspecs/common/gcc-base.conf \
		../opt/anaconda3/mkspecs/common/gcc-base-mac.conf \
		../opt/anaconda3/mkspecs/common/clang.conf \
		../opt/anaconda3/mkspecs/common/clang-mac.conf \
		../opt/anaconda3/mkspecs/qconfig.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_core.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_help.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_location.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_macextras.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_macextras_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_network.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_script.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../opt/anaconda3/mkspecs/features/qt_functions.prf \
		../opt/anaconda3/mkspecs/features/qt_config.prf \
		../opt/anaconda3/mkspecs/macx-clang/qmake.conf \
		../opt/anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../opt/anaconda3/mkspecs/features/exclusive_builds.prf \
		../opt/anaconda3/mkspecs/features/mac/sdk.prf \
		../opt/anaconda3/mkspecs/features/toolchain.prf \
		../opt/anaconda3/mkspecs/features/mac/toolchain.prf \
		../opt/anaconda3/mkspecs/features/default_pre.prf \
		../opt/anaconda3/mkspecs/features/mac/default_pre.prf \
		../opt/anaconda3/mkspecs/features/resolve_config.prf \
		../opt/anaconda3/mkspecs/features/default_post.prf \
		../opt/anaconda3/mkspecs/features/mac/default_post.prf \
		../opt/anaconda3/mkspecs/features/mac/objective_c.prf \
		../opt/anaconda3/mkspecs/features/warn_on.prf \
		../opt/anaconda3/mkspecs/features/qt.prf \
		../opt/anaconda3/mkspecs/features/resources.prf \
		../opt/anaconda3/mkspecs/features/moc.prf \
		../opt/anaconda3/mkspecs/features/unix/opengl.prf \
		../opt/anaconda3/mkspecs/features/uic.prf \
		../opt/anaconda3/mkspecs/features/unix/thread.prf \
		../opt/anaconda3/mkspecs/features/qmake_use.prf \
		../opt/anaconda3/mkspecs/features/file_copies.prf \
		../opt/anaconda3/mkspecs/features/mac/rez.prf \
		../opt/anaconda3/mkspecs/features/mac/asset_catalogs.prf \
		../opt/anaconda3/mkspecs/features/testcase_targets.prf \
		../opt/anaconda3/mkspecs/features/exceptions.prf \
		../opt/anaconda3/mkspecs/features/yacc.prf \
		../opt/anaconda3/mkspecs/features/lex.prf \
		MineSweeper.pro CellButton.h \
		GameBoard.h \
		MainWindow.h main.cpp \
		GameBoard.cpp \
		MainWindow.cpp \
		CellButton.cpp
QMAKE_TARGET  = myapp
DESTDIR       = 
TARGET        = myapp.app/Contents/MacOS/myapp

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d myapp.app/Contents/MacOS/ || mkdir -p myapp.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MineSweeper.pro ../opt/anaconda3/mkspecs/macx-clang/qmake.conf ../opt/anaconda3/mkspecs/features/spec_pre.prf \
		../opt/anaconda3/mkspecs/qdevice.pri \
		../opt/anaconda3/mkspecs/features/device_config.prf \
		../opt/anaconda3/mkspecs/common/unix.conf \
		../opt/anaconda3/mkspecs/common/mac.conf \
		../opt/anaconda3/mkspecs/common/macx.conf \
		../opt/anaconda3/mkspecs/common/sanitize.conf \
		../opt/anaconda3/mkspecs/common/gcc-base.conf \
		../opt/anaconda3/mkspecs/common/gcc-base-mac.conf \
		../opt/anaconda3/mkspecs/common/clang.conf \
		../opt/anaconda3/mkspecs/common/clang-mac.conf \
		../opt/anaconda3/mkspecs/qconfig.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_core.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_help.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_location.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_macextras.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_macextras_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_network.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_script.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../opt/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../opt/anaconda3/mkspecs/features/qt_functions.prf \
		../opt/anaconda3/mkspecs/features/qt_config.prf \
		../opt/anaconda3/mkspecs/macx-clang/qmake.conf \
		../opt/anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../opt/anaconda3/mkspecs/features/exclusive_builds.prf \
		../opt/anaconda3/mkspecs/features/mac/sdk.prf \
		../opt/anaconda3/mkspecs/features/toolchain.prf \
		../opt/anaconda3/mkspecs/features/mac/toolchain.prf \
		../opt/anaconda3/mkspecs/features/default_pre.prf \
		../opt/anaconda3/mkspecs/features/mac/default_pre.prf \
		../opt/anaconda3/mkspecs/features/resolve_config.prf \
		../opt/anaconda3/mkspecs/features/default_post.prf \
		../opt/anaconda3/mkspecs/features/mac/default_post.prf \
		../opt/anaconda3/mkspecs/features/mac/objective_c.prf \
		../opt/anaconda3/mkspecs/features/warn_on.prf \
		../opt/anaconda3/mkspecs/features/qt.prf \
		../opt/anaconda3/mkspecs/features/resources.prf \
		../opt/anaconda3/mkspecs/features/moc.prf \
		../opt/anaconda3/mkspecs/features/unix/opengl.prf \
		../opt/anaconda3/mkspecs/features/uic.prf \
		../opt/anaconda3/mkspecs/features/unix/thread.prf \
		../opt/anaconda3/mkspecs/features/qmake_use.prf \
		../opt/anaconda3/mkspecs/features/file_copies.prf \
		../opt/anaconda3/mkspecs/features/mac/rez.prf \
		../opt/anaconda3/mkspecs/features/mac/asset_catalogs.prf \
		../opt/anaconda3/mkspecs/features/testcase_targets.prf \
		../opt/anaconda3/mkspecs/features/exceptions.prf \
		../opt/anaconda3/mkspecs/features/yacc.prf \
		../opt/anaconda3/mkspecs/features/lex.prf \
		MineSweeper.pro \
		resources/minesweeper_icons/images.qrc \
		../opt/anaconda3/lib/libQt5Widgets.prl \
		../opt/anaconda3/lib/libQt5Gui.prl \
		../opt/anaconda3/lib/libQt5Core.prl
	$(QMAKE) -o Makefile MineSweeper.pro
../opt/anaconda3/mkspecs/features/spec_pre.prf:
../opt/anaconda3/mkspecs/qdevice.pri:
../opt/anaconda3/mkspecs/features/device_config.prf:
../opt/anaconda3/mkspecs/common/unix.conf:
../opt/anaconda3/mkspecs/common/mac.conf:
../opt/anaconda3/mkspecs/common/macx.conf:
../opt/anaconda3/mkspecs/common/sanitize.conf:
../opt/anaconda3/mkspecs/common/gcc-base.conf:
../opt/anaconda3/mkspecs/common/gcc-base-mac.conf:
../opt/anaconda3/mkspecs/common/clang.conf:
../opt/anaconda3/mkspecs/common/clang-mac.conf:
../opt/anaconda3/mkspecs/qconfig.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3danimation.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dcore.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dextras.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dinput.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dquick.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3drender.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_cgl_support_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_charts.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_charts_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_core.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_core_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_dbus.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_designer.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_designer_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_gamepad.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_graphics_support_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_gui.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_help.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_help_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_location.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_location_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_macextras.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_macextras_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_network.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_network_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_networkauth.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_nfc.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_opengl.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_positioning.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_purchasing.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_qml.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_quick.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_repparser.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_script.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_script_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_scxml.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_sensors.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_serialbus.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_serialport.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_sql.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_svg.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_testlib.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_uitools.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_webengine.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_websockets.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_webview.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_webview_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_widgets.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_xml.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
../opt/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../opt/anaconda3/mkspecs/features/qt_functions.prf:
../opt/anaconda3/mkspecs/features/qt_config.prf:
../opt/anaconda3/mkspecs/macx-clang/qmake.conf:
../opt/anaconda3/mkspecs/features/spec_post.prf:
.qmake.stash:
../opt/anaconda3/mkspecs/features/exclusive_builds.prf:
../opt/anaconda3/mkspecs/features/mac/sdk.prf:
../opt/anaconda3/mkspecs/features/toolchain.prf:
../opt/anaconda3/mkspecs/features/mac/toolchain.prf:
../opt/anaconda3/mkspecs/features/default_pre.prf:
../opt/anaconda3/mkspecs/features/mac/default_pre.prf:
../opt/anaconda3/mkspecs/features/resolve_config.prf:
../opt/anaconda3/mkspecs/features/default_post.prf:
../opt/anaconda3/mkspecs/features/mac/default_post.prf:
../opt/anaconda3/mkspecs/features/mac/objective_c.prf:
../opt/anaconda3/mkspecs/features/warn_on.prf:
../opt/anaconda3/mkspecs/features/qt.prf:
../opt/anaconda3/mkspecs/features/resources.prf:
../opt/anaconda3/mkspecs/features/moc.prf:
../opt/anaconda3/mkspecs/features/unix/opengl.prf:
../opt/anaconda3/mkspecs/features/uic.prf:
../opt/anaconda3/mkspecs/features/unix/thread.prf:
../opt/anaconda3/mkspecs/features/qmake_use.prf:
../opt/anaconda3/mkspecs/features/file_copies.prf:
../opt/anaconda3/mkspecs/features/mac/rez.prf:
../opt/anaconda3/mkspecs/features/mac/asset_catalogs.prf:
../opt/anaconda3/mkspecs/features/testcase_targets.prf:
../opt/anaconda3/mkspecs/features/exceptions.prf:
../opt/anaconda3/mkspecs/features/yacc.prf:
../opt/anaconda3/mkspecs/features/lex.prf:
MineSweeper.pro:
resources/minesweeper_icons/images.qrc:
../opt/anaconda3/lib/libQt5Widgets.prl:
../opt/anaconda3/lib/libQt5Gui.prl:
../opt/anaconda3/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MineSweeper.pro

qmake_all: FORCE

myapp.app/Contents/PkgInfo: 
	@test -d myapp.app/Contents || mkdir -p myapp.app/Contents
	@$(DEL_FILE) myapp.app/Contents/PkgInfo
	@echo "APPL????" > myapp.app/Contents/PkgInfo
myapp.app/Contents/Resources/empty.lproj: 
	@test -d myapp.app/Contents/Resources || mkdir -p myapp.app/Contents/Resources
	@touch myapp.app/Contents/Resources/empty.lproj
	
myapp.app/Contents/Info.plist: 
	@test -d myapp.app/Contents || mkdir -p myapp.app/Contents
	@$(DEL_FILE) myapp.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.myapp,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,myapp,g" -e "s,@LIBRARY@,myapp,g" -e "s,@TYPEINFO@,????,g" ../opt/anaconda3/mkspecs/macx-clang/Info.plist.app >myapp.app/Contents/Info.plist

all: Makefile \
		myapp.app/Contents/PkgInfo \
		myapp.app/Contents/Resources/empty.lproj \
		myapp.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources/minesweeper_icons/images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../opt/anaconda3/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents CellButton.h GameBoard.h MainWindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp GameBoard.cpp MainWindow.cpp CellButton.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r myapp.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: resources/minesweeper_icons/images.qrc \
		../opt/anaconda3/bin/rcc \
		resources/minesweeper_icons/bomb.png \
		resources/minesweeper_icons/mine_flag.png \
		resources/minesweeper_icons/bomb_explode.png \
		resources/minesweeper_icons/bomb_explode_sm.png
	/Users/taejunha/opt/anaconda3/bin/rcc -name images resources/minesweeper_icons/images.qrc -o qrc_images.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../opt/anaconda3/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -Wno-deprecated-copy -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h ../opt/anaconda3/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_CellButton.cpp moc_GameBoard.cpp moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_CellButton.cpp moc_GameBoard.cpp moc_MainWindow.cpp
moc_CellButton.cpp: ../opt/anaconda3/include/qt/QtWidgets/QPushButton \
		../opt/anaconda3/include/qt/QtWidgets/qpushbutton.h \
		../opt/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../opt/anaconda3/include/qt/QtGui/qtguiglobal.h \
		../opt/anaconda3/include/qt/QtCore/qglobal.h \
		../opt/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../opt/anaconda3/include/qt/QtCore/qconfig.h \
		../opt/anaconda3/include/qt/QtCore/qtcore-config.h \
		../opt/anaconda3/include/qt/QtCore/qsystemdetection.h \
		../opt/anaconda3/include/qt/QtCore/qprocessordetection.h \
		../opt/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../opt/anaconda3/include/qt/QtCore/qtypeinfo.h \
		../opt/anaconda3/include/qt/QtCore/qsysinfo.h \
		../opt/anaconda3/include/qt/QtCore/qlogging.h \
		../opt/anaconda3/include/qt/QtCore/qflags.h \
		../opt/anaconda3/include/qt/QtCore/qatomic.h \
		../opt/anaconda3/include/qt/QtCore/qbasicatomic.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../opt/anaconda3/include/qt/QtCore/qgenericatomic.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../opt/anaconda3/include/qt/QtCore/qglobalstatic.h \
		../opt/anaconda3/include/qt/QtCore/qmutex.h \
		../opt/anaconda3/include/qt/QtCore/qnumeric.h \
		../opt/anaconda3/include/qt/QtCore/qversiontagging.h \
		../opt/anaconda3/include/qt/QtGui/qtgui-config.h \
		../opt/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../opt/anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		../opt/anaconda3/include/qt/QtGui/qicon.h \
		../opt/anaconda3/include/qt/QtCore/qsize.h \
		../opt/anaconda3/include/qt/QtCore/qnamespace.h \
		../opt/anaconda3/include/qt/QtCore/qlist.h \
		../opt/anaconda3/include/qt/QtCore/qalgorithms.h \
		../opt/anaconda3/include/qt/QtCore/qiterator.h \
		../opt/anaconda3/include/qt/QtCore/qrefcount.h \
		../opt/anaconda3/include/qt/QtCore/qarraydata.h \
		../opt/anaconda3/include/qt/QtCore/qhashfunctions.h \
		../opt/anaconda3/include/qt/QtCore/qchar.h \
		../opt/anaconda3/include/qt/QtCore/qpair.h \
		../opt/anaconda3/include/qt/QtCore/qbytearraylist.h \
		../opt/anaconda3/include/qt/QtCore/qbytearray.h \
		../opt/anaconda3/include/qt/QtCore/qstring.h \
		../opt/anaconda3/include/qt/QtCore/qstringbuilder.h \
		../opt/anaconda3/include/qt/QtCore/qstringlist.h \
		../opt/anaconda3/include/qt/QtCore/qregexp.h \
		../opt/anaconda3/include/qt/QtCore/qstringmatcher.h \
		../opt/anaconda3/include/qt/QtGui/qpixmap.h \
		../opt/anaconda3/include/qt/QtGui/qpaintdevice.h \
		../opt/anaconda3/include/qt/QtGui/qwindowdefs.h \
		../opt/anaconda3/include/qt/QtCore/qobjectdefs.h \
		../opt/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../opt/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../opt/anaconda3/include/qt/QtCore/qrect.h \
		../opt/anaconda3/include/qt/QtCore/qmargins.h \
		../opt/anaconda3/include/qt/QtCore/qpoint.h \
		../opt/anaconda3/include/qt/QtGui/qcolor.h \
		../opt/anaconda3/include/qt/QtGui/qrgb.h \
		../opt/anaconda3/include/qt/QtGui/qrgba64.h \
		../opt/anaconda3/include/qt/QtCore/qsharedpointer.h \
		../opt/anaconda3/include/qt/QtCore/qshareddata.h \
		../opt/anaconda3/include/qt/QtCore/qhash.h \
		../opt/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../opt/anaconda3/include/qt/QtCore/qobject.h \
		../opt/anaconda3/include/qt/QtCore/qcoreevent.h \
		../opt/anaconda3/include/qt/QtCore/qscopedpointer.h \
		../opt/anaconda3/include/qt/QtCore/qmetatype.h \
		../opt/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../opt/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../opt/anaconda3/include/qt/QtCore/qobject_impl.h \
		../opt/anaconda3/include/qt/QtGui/qimage.h \
		../opt/anaconda3/include/qt/QtGui/qpixelformat.h \
		../opt/anaconda3/include/qt/QtGui/qtransform.h \
		../opt/anaconda3/include/qt/QtGui/qmatrix.h \
		../opt/anaconda3/include/qt/QtGui/qpolygon.h \
		../opt/anaconda3/include/qt/QtCore/qvector.h \
		../opt/anaconda3/include/qt/QtGui/qregion.h \
		../opt/anaconda3/include/qt/QtCore/qdatastream.h \
		../opt/anaconda3/include/qt/QtCore/qiodevice.h \
		../opt/anaconda3/include/qt/QtCore/qline.h \
		../opt/anaconda3/include/qt/QtGui/qpainterpath.h \
		../opt/anaconda3/include/qt/QtGui/qkeysequence.h \
		../opt/anaconda3/include/qt/QtWidgets/qwidget.h \
		../opt/anaconda3/include/qt/QtGui/qpalette.h \
		../opt/anaconda3/include/qt/QtGui/qbrush.h \
		../opt/anaconda3/include/qt/QtGui/qfont.h \
		../opt/anaconda3/include/qt/QtGui/qfontmetrics.h \
		../opt/anaconda3/include/qt/QtGui/qfontinfo.h \
		../opt/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../opt/anaconda3/include/qt/QtGui/qcursor.h \
		../opt/anaconda3/include/qt/QtGui/qevent.h \
		../opt/anaconda3/include/qt/QtCore/qvariant.h \
		../opt/anaconda3/include/qt/QtCore/qmap.h \
		../opt/anaconda3/include/qt/QtCore/qdebug.h \
		../opt/anaconda3/include/qt/QtCore/qtextstream.h \
		../opt/anaconda3/include/qt/QtCore/qlocale.h \
		../opt/anaconda3/include/qt/QtCore/qset.h \
		../opt/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../opt/anaconda3/include/qt/QtCore/qurl.h \
		../opt/anaconda3/include/qt/QtCore/qurlquery.h \
		../opt/anaconda3/include/qt/QtCore/qfile.h \
		../opt/anaconda3/include/qt/QtCore/qfiledevice.h \
		../opt/anaconda3/include/qt/QtGui/qvector2d.h \
		../opt/anaconda3/include/qt/QtGui/qtouchdevice.h \
		../opt/anaconda3/include/qt/QtGui/QMouseEvent \
		CellButton.h \
		moc_predefs.h \
		../opt/anaconda3/bin/moc
	/Users/taejunha/opt/anaconda3/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/taejunha/opt/anaconda3/mkspecs/macx-clang -I/Users/taejunha/3307assignment1 -I/Users/taejunha/opt/anaconda3/include/qt -I/Users/taejunha/opt/anaconda3/include/qt/QtWidgets -I/Users/taejunha/opt/anaconda3/include/qt/QtGui -I/Users/taejunha/opt/anaconda3/include/qt/QtCore -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include CellButton.h -o moc_CellButton.cpp

moc_GameBoard.cpp: ../opt/anaconda3/include/qt/QtWidgets/QWidget \
		../opt/anaconda3/include/qt/QtWidgets/qwidget.h \
		../opt/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../opt/anaconda3/include/qt/QtGui/qtguiglobal.h \
		../opt/anaconda3/include/qt/QtCore/qglobal.h \
		../opt/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../opt/anaconda3/include/qt/QtCore/qconfig.h \
		../opt/anaconda3/include/qt/QtCore/qtcore-config.h \
		../opt/anaconda3/include/qt/QtCore/qsystemdetection.h \
		../opt/anaconda3/include/qt/QtCore/qprocessordetection.h \
		../opt/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../opt/anaconda3/include/qt/QtCore/qtypeinfo.h \
		../opt/anaconda3/include/qt/QtCore/qsysinfo.h \
		../opt/anaconda3/include/qt/QtCore/qlogging.h \
		../opt/anaconda3/include/qt/QtCore/qflags.h \
		../opt/anaconda3/include/qt/QtCore/qatomic.h \
		../opt/anaconda3/include/qt/QtCore/qbasicatomic.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../opt/anaconda3/include/qt/QtCore/qgenericatomic.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../opt/anaconda3/include/qt/QtCore/qglobalstatic.h \
		../opt/anaconda3/include/qt/QtCore/qmutex.h \
		../opt/anaconda3/include/qt/QtCore/qnumeric.h \
		../opt/anaconda3/include/qt/QtCore/qversiontagging.h \
		../opt/anaconda3/include/qt/QtGui/qtgui-config.h \
		../opt/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../opt/anaconda3/include/qt/QtGui/qwindowdefs.h \
		../opt/anaconda3/include/qt/QtCore/qobjectdefs.h \
		../opt/anaconda3/include/qt/QtCore/qnamespace.h \
		../opt/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../opt/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../opt/anaconda3/include/qt/QtCore/qobject.h \
		../opt/anaconda3/include/qt/QtCore/qstring.h \
		../opt/anaconda3/include/qt/QtCore/qchar.h \
		../opt/anaconda3/include/qt/QtCore/qbytearray.h \
		../opt/anaconda3/include/qt/QtCore/qrefcount.h \
		../opt/anaconda3/include/qt/QtCore/qarraydata.h \
		../opt/anaconda3/include/qt/QtCore/qstringbuilder.h \
		../opt/anaconda3/include/qt/QtCore/qlist.h \
		../opt/anaconda3/include/qt/QtCore/qalgorithms.h \
		../opt/anaconda3/include/qt/QtCore/qiterator.h \
		../opt/anaconda3/include/qt/QtCore/qhashfunctions.h \
		../opt/anaconda3/include/qt/QtCore/qpair.h \
		../opt/anaconda3/include/qt/QtCore/qbytearraylist.h \
		../opt/anaconda3/include/qt/QtCore/qstringlist.h \
		../opt/anaconda3/include/qt/QtCore/qregexp.h \
		../opt/anaconda3/include/qt/QtCore/qstringmatcher.h \
		../opt/anaconda3/include/qt/QtCore/qcoreevent.h \
		../opt/anaconda3/include/qt/QtCore/qscopedpointer.h \
		../opt/anaconda3/include/qt/QtCore/qmetatype.h \
		../opt/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../opt/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../opt/anaconda3/include/qt/QtCore/qobject_impl.h \
		../opt/anaconda3/include/qt/QtCore/qmargins.h \
		../opt/anaconda3/include/qt/QtGui/qpaintdevice.h \
		../opt/anaconda3/include/qt/QtCore/qrect.h \
		../opt/anaconda3/include/qt/QtCore/qsize.h \
		../opt/anaconda3/include/qt/QtCore/qpoint.h \
		../opt/anaconda3/include/qt/QtGui/qpalette.h \
		../opt/anaconda3/include/qt/QtGui/qcolor.h \
		../opt/anaconda3/include/qt/QtGui/qrgb.h \
		../opt/anaconda3/include/qt/QtGui/qrgba64.h \
		../opt/anaconda3/include/qt/QtGui/qbrush.h \
		../opt/anaconda3/include/qt/QtCore/qvector.h \
		../opt/anaconda3/include/qt/QtGui/qmatrix.h \
		../opt/anaconda3/include/qt/QtGui/qpolygon.h \
		../opt/anaconda3/include/qt/QtGui/qregion.h \
		../opt/anaconda3/include/qt/QtCore/qdatastream.h \
		../opt/anaconda3/include/qt/QtCore/qiodevice.h \
		../opt/anaconda3/include/qt/QtCore/qline.h \
		../opt/anaconda3/include/qt/QtGui/qtransform.h \
		../opt/anaconda3/include/qt/QtGui/qpainterpath.h \
		../opt/anaconda3/include/qt/QtGui/qimage.h \
		../opt/anaconda3/include/qt/QtGui/qpixelformat.h \
		../opt/anaconda3/include/qt/QtGui/qpixmap.h \
		../opt/anaconda3/include/qt/QtCore/qsharedpointer.h \
		../opt/anaconda3/include/qt/QtCore/qshareddata.h \
		../opt/anaconda3/include/qt/QtCore/qhash.h \
		../opt/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../opt/anaconda3/include/qt/QtGui/qfont.h \
		../opt/anaconda3/include/qt/QtGui/qfontmetrics.h \
		../opt/anaconda3/include/qt/QtGui/qfontinfo.h \
		../opt/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../opt/anaconda3/include/qt/QtGui/qcursor.h \
		../opt/anaconda3/include/qt/QtGui/qkeysequence.h \
		../opt/anaconda3/include/qt/QtGui/qevent.h \
		../opt/anaconda3/include/qt/QtCore/qvariant.h \
		../opt/anaconda3/include/qt/QtCore/qmap.h \
		../opt/anaconda3/include/qt/QtCore/qdebug.h \
		../opt/anaconda3/include/qt/QtCore/qtextstream.h \
		../opt/anaconda3/include/qt/QtCore/qlocale.h \
		../opt/anaconda3/include/qt/QtCore/qset.h \
		../opt/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../opt/anaconda3/include/qt/QtCore/qurl.h \
		../opt/anaconda3/include/qt/QtCore/qurlquery.h \
		../opt/anaconda3/include/qt/QtCore/qfile.h \
		../opt/anaconda3/include/qt/QtCore/qfiledevice.h \
		../opt/anaconda3/include/qt/QtGui/qvector2d.h \
		../opt/anaconda3/include/qt/QtGui/qtouchdevice.h \
		../opt/anaconda3/include/qt/QtWidgets/QGridLayout \
		../opt/anaconda3/include/qt/QtWidgets/qgridlayout.h \
		../opt/anaconda3/include/qt/QtWidgets/qlayout.h \
		../opt/anaconda3/include/qt/QtWidgets/qlayoutitem.h \
		../opt/anaconda3/include/qt/QtWidgets/qboxlayout.h \
		CellButton.h \
		../opt/anaconda3/include/qt/QtWidgets/QPushButton \
		../opt/anaconda3/include/qt/QtWidgets/qpushbutton.h \
		../opt/anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		../opt/anaconda3/include/qt/QtGui/qicon.h \
		../opt/anaconda3/include/qt/QtGui/QMouseEvent \
		GameBoard.h \
		moc_predefs.h \
		../opt/anaconda3/bin/moc
	/Users/taejunha/opt/anaconda3/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/taejunha/opt/anaconda3/mkspecs/macx-clang -I/Users/taejunha/3307assignment1 -I/Users/taejunha/opt/anaconda3/include/qt -I/Users/taejunha/opt/anaconda3/include/qt/QtWidgets -I/Users/taejunha/opt/anaconda3/include/qt/QtGui -I/Users/taejunha/opt/anaconda3/include/qt/QtCore -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include GameBoard.h -o moc_GameBoard.cpp

moc_MainWindow.cpp: ../opt/anaconda3/include/qt/QtWidgets/QMainWindow \
		../opt/anaconda3/include/qt/QtWidgets/qmainwindow.h \
		../opt/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../opt/anaconda3/include/qt/QtGui/qtguiglobal.h \
		../opt/anaconda3/include/qt/QtCore/qglobal.h \
		../opt/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../opt/anaconda3/include/qt/QtCore/qconfig.h \
		../opt/anaconda3/include/qt/QtCore/qtcore-config.h \
		../opt/anaconda3/include/qt/QtCore/qsystemdetection.h \
		../opt/anaconda3/include/qt/QtCore/qprocessordetection.h \
		../opt/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../opt/anaconda3/include/qt/QtCore/qtypeinfo.h \
		../opt/anaconda3/include/qt/QtCore/qsysinfo.h \
		../opt/anaconda3/include/qt/QtCore/qlogging.h \
		../opt/anaconda3/include/qt/QtCore/qflags.h \
		../opt/anaconda3/include/qt/QtCore/qatomic.h \
		../opt/anaconda3/include/qt/QtCore/qbasicatomic.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../opt/anaconda3/include/qt/QtCore/qgenericatomic.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../opt/anaconda3/include/qt/QtCore/qglobalstatic.h \
		../opt/anaconda3/include/qt/QtCore/qmutex.h \
		../opt/anaconda3/include/qt/QtCore/qnumeric.h \
		../opt/anaconda3/include/qt/QtCore/qversiontagging.h \
		../opt/anaconda3/include/qt/QtGui/qtgui-config.h \
		../opt/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../opt/anaconda3/include/qt/QtWidgets/qwidget.h \
		../opt/anaconda3/include/qt/QtGui/qwindowdefs.h \
		../opt/anaconda3/include/qt/QtCore/qobjectdefs.h \
		../opt/anaconda3/include/qt/QtCore/qnamespace.h \
		../opt/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../opt/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../opt/anaconda3/include/qt/QtCore/qobject.h \
		../opt/anaconda3/include/qt/QtCore/qstring.h \
		../opt/anaconda3/include/qt/QtCore/qchar.h \
		../opt/anaconda3/include/qt/QtCore/qbytearray.h \
		../opt/anaconda3/include/qt/QtCore/qrefcount.h \
		../opt/anaconda3/include/qt/QtCore/qarraydata.h \
		../opt/anaconda3/include/qt/QtCore/qstringbuilder.h \
		../opt/anaconda3/include/qt/QtCore/qlist.h \
		../opt/anaconda3/include/qt/QtCore/qalgorithms.h \
		../opt/anaconda3/include/qt/QtCore/qiterator.h \
		../opt/anaconda3/include/qt/QtCore/qhashfunctions.h \
		../opt/anaconda3/include/qt/QtCore/qpair.h \
		../opt/anaconda3/include/qt/QtCore/qbytearraylist.h \
		../opt/anaconda3/include/qt/QtCore/qstringlist.h \
		../opt/anaconda3/include/qt/QtCore/qregexp.h \
		../opt/anaconda3/include/qt/QtCore/qstringmatcher.h \
		../opt/anaconda3/include/qt/QtCore/qcoreevent.h \
		../opt/anaconda3/include/qt/QtCore/qscopedpointer.h \
		../opt/anaconda3/include/qt/QtCore/qmetatype.h \
		../opt/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../opt/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../opt/anaconda3/include/qt/QtCore/qobject_impl.h \
		../opt/anaconda3/include/qt/QtCore/qmargins.h \
		../opt/anaconda3/include/qt/QtGui/qpaintdevice.h \
		../opt/anaconda3/include/qt/QtCore/qrect.h \
		../opt/anaconda3/include/qt/QtCore/qsize.h \
		../opt/anaconda3/include/qt/QtCore/qpoint.h \
		../opt/anaconda3/include/qt/QtGui/qpalette.h \
		../opt/anaconda3/include/qt/QtGui/qcolor.h \
		../opt/anaconda3/include/qt/QtGui/qrgb.h \
		../opt/anaconda3/include/qt/QtGui/qrgba64.h \
		../opt/anaconda3/include/qt/QtGui/qbrush.h \
		../opt/anaconda3/include/qt/QtCore/qvector.h \
		../opt/anaconda3/include/qt/QtGui/qmatrix.h \
		../opt/anaconda3/include/qt/QtGui/qpolygon.h \
		../opt/anaconda3/include/qt/QtGui/qregion.h \
		../opt/anaconda3/include/qt/QtCore/qdatastream.h \
		../opt/anaconda3/include/qt/QtCore/qiodevice.h \
		../opt/anaconda3/include/qt/QtCore/qline.h \
		../opt/anaconda3/include/qt/QtGui/qtransform.h \
		../opt/anaconda3/include/qt/QtGui/qpainterpath.h \
		../opt/anaconda3/include/qt/QtGui/qimage.h \
		../opt/anaconda3/include/qt/QtGui/qpixelformat.h \
		../opt/anaconda3/include/qt/QtGui/qpixmap.h \
		../opt/anaconda3/include/qt/QtCore/qsharedpointer.h \
		../opt/anaconda3/include/qt/QtCore/qshareddata.h \
		../opt/anaconda3/include/qt/QtCore/qhash.h \
		../opt/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../opt/anaconda3/include/qt/QtGui/qfont.h \
		../opt/anaconda3/include/qt/QtGui/qfontmetrics.h \
		../opt/anaconda3/include/qt/QtGui/qfontinfo.h \
		../opt/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../opt/anaconda3/include/qt/QtGui/qcursor.h \
		../opt/anaconda3/include/qt/QtGui/qkeysequence.h \
		../opt/anaconda3/include/qt/QtGui/qevent.h \
		../opt/anaconda3/include/qt/QtCore/qvariant.h \
		../opt/anaconda3/include/qt/QtCore/qmap.h \
		../opt/anaconda3/include/qt/QtCore/qdebug.h \
		../opt/anaconda3/include/qt/QtCore/qtextstream.h \
		../opt/anaconda3/include/qt/QtCore/qlocale.h \
		../opt/anaconda3/include/qt/QtCore/qset.h \
		../opt/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../opt/anaconda3/include/qt/QtCore/qurl.h \
		../opt/anaconda3/include/qt/QtCore/qurlquery.h \
		../opt/anaconda3/include/qt/QtCore/qfile.h \
		../opt/anaconda3/include/qt/QtCore/qfiledevice.h \
		../opt/anaconda3/include/qt/QtGui/qvector2d.h \
		../opt/anaconda3/include/qt/QtGui/qtouchdevice.h \
		../opt/anaconda3/include/qt/QtWidgets/qtabwidget.h \
		../opt/anaconda3/include/qt/QtGui/qicon.h \
		GameBoard.h \
		../opt/anaconda3/include/qt/QtWidgets/QWidget \
		../opt/anaconda3/include/qt/QtWidgets/QGridLayout \
		../opt/anaconda3/include/qt/QtWidgets/qgridlayout.h \
		../opt/anaconda3/include/qt/QtWidgets/qlayout.h \
		../opt/anaconda3/include/qt/QtWidgets/qlayoutitem.h \
		../opt/anaconda3/include/qt/QtWidgets/qboxlayout.h \
		CellButton.h \
		../opt/anaconda3/include/qt/QtWidgets/QPushButton \
		../opt/anaconda3/include/qt/QtWidgets/qpushbutton.h \
		../opt/anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		../opt/anaconda3/include/qt/QtGui/QMouseEvent \
		MainWindow.h \
		moc_predefs.h \
		../opt/anaconda3/bin/moc
	/Users/taejunha/opt/anaconda3/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/taejunha/opt/anaconda3/mkspecs/macx-clang -I/Users/taejunha/3307assignment1 -I/Users/taejunha/opt/anaconda3/include/qt -I/Users/taejunha/opt/anaconda3/include/qt/QtWidgets -I/Users/taejunha/opt/anaconda3/include/qt/QtGui -I/Users/taejunha/opt/anaconda3/include/qt/QtCore -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include MainWindow.h -o moc_MainWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../opt/anaconda3/include/qt/QtWidgets/QApplication \
		../opt/anaconda3/include/qt/QtWidgets/qapplication.h \
		../opt/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../opt/anaconda3/include/qt/QtGui/qtguiglobal.h \
		../opt/anaconda3/include/qt/QtCore/qglobal.h \
		../opt/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../opt/anaconda3/include/qt/QtCore/qconfig.h \
		../opt/anaconda3/include/qt/QtCore/qtcore-config.h \
		../opt/anaconda3/include/qt/QtCore/qsystemdetection.h \
		../opt/anaconda3/include/qt/QtCore/qprocessordetection.h \
		../opt/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../opt/anaconda3/include/qt/QtCore/qtypeinfo.h \
		../opt/anaconda3/include/qt/QtCore/qsysinfo.h \
		../opt/anaconda3/include/qt/QtCore/qlogging.h \
		../opt/anaconda3/include/qt/QtCore/qflags.h \
		../opt/anaconda3/include/qt/QtCore/qatomic.h \
		../opt/anaconda3/include/qt/QtCore/qbasicatomic.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../opt/anaconda3/include/qt/QtCore/qgenericatomic.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../opt/anaconda3/include/qt/QtCore/qglobalstatic.h \
		../opt/anaconda3/include/qt/QtCore/qmutex.h \
		../opt/anaconda3/include/qt/QtCore/qnumeric.h \
		../opt/anaconda3/include/qt/QtCore/qversiontagging.h \
		../opt/anaconda3/include/qt/QtGui/qtgui-config.h \
		../opt/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../opt/anaconda3/include/qt/QtCore/qcoreapplication.h \
		../opt/anaconda3/include/qt/QtCore/qstring.h \
		../opt/anaconda3/include/qt/QtCore/qchar.h \
		../opt/anaconda3/include/qt/QtCore/qbytearray.h \
		../opt/anaconda3/include/qt/QtCore/qrefcount.h \
		../opt/anaconda3/include/qt/QtCore/qnamespace.h \
		../opt/anaconda3/include/qt/QtCore/qarraydata.h \
		../opt/anaconda3/include/qt/QtCore/qstringbuilder.h \
		../opt/anaconda3/include/qt/QtCore/qobject.h \
		../opt/anaconda3/include/qt/QtCore/qobjectdefs.h \
		../opt/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../opt/anaconda3/include/qt/QtCore/qlist.h \
		../opt/anaconda3/include/qt/QtCore/qalgorithms.h \
		../opt/anaconda3/include/qt/QtCore/qiterator.h \
		../opt/anaconda3/include/qt/QtCore/qhashfunctions.h \
		../opt/anaconda3/include/qt/QtCore/qpair.h \
		../opt/anaconda3/include/qt/QtCore/qbytearraylist.h \
		../opt/anaconda3/include/qt/QtCore/qstringlist.h \
		../opt/anaconda3/include/qt/QtCore/qregexp.h \
		../opt/anaconda3/include/qt/QtCore/qstringmatcher.h \
		../opt/anaconda3/include/qt/QtCore/qcoreevent.h \
		../opt/anaconda3/include/qt/QtCore/qscopedpointer.h \
		../opt/anaconda3/include/qt/QtCore/qmetatype.h \
		../opt/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../opt/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../opt/anaconda3/include/qt/QtCore/qobject_impl.h \
		../opt/anaconda3/include/qt/QtCore/qeventloop.h \
		../opt/anaconda3/include/qt/QtGui/qwindowdefs.h \
		../opt/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../opt/anaconda3/include/qt/QtCore/qpoint.h \
		../opt/anaconda3/include/qt/QtCore/qsize.h \
		../opt/anaconda3/include/qt/QtGui/qcursor.h \
		../opt/anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		../opt/anaconda3/include/qt/QtWidgets/qwidget.h \
		../opt/anaconda3/include/qt/QtCore/qmargins.h \
		../opt/anaconda3/include/qt/QtGui/qpaintdevice.h \
		../opt/anaconda3/include/qt/QtCore/qrect.h \
		../opt/anaconda3/include/qt/QtGui/qpalette.h \
		../opt/anaconda3/include/qt/QtGui/qcolor.h \
		../opt/anaconda3/include/qt/QtGui/qrgb.h \
		../opt/anaconda3/include/qt/QtGui/qrgba64.h \
		../opt/anaconda3/include/qt/QtGui/qbrush.h \
		../opt/anaconda3/include/qt/QtCore/qvector.h \
		../opt/anaconda3/include/qt/QtGui/qmatrix.h \
		../opt/anaconda3/include/qt/QtGui/qpolygon.h \
		../opt/anaconda3/include/qt/QtGui/qregion.h \
		../opt/anaconda3/include/qt/QtCore/qdatastream.h \
		../opt/anaconda3/include/qt/QtCore/qiodevice.h \
		../opt/anaconda3/include/qt/QtCore/qline.h \
		../opt/anaconda3/include/qt/QtGui/qtransform.h \
		../opt/anaconda3/include/qt/QtGui/qpainterpath.h \
		../opt/anaconda3/include/qt/QtGui/qimage.h \
		../opt/anaconda3/include/qt/QtGui/qpixelformat.h \
		../opt/anaconda3/include/qt/QtGui/qpixmap.h \
		../opt/anaconda3/include/qt/QtCore/qsharedpointer.h \
		../opt/anaconda3/include/qt/QtCore/qshareddata.h \
		../opt/anaconda3/include/qt/QtCore/qhash.h \
		../opt/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../opt/anaconda3/include/qt/QtGui/qfont.h \
		../opt/anaconda3/include/qt/QtGui/qfontmetrics.h \
		../opt/anaconda3/include/qt/QtGui/qfontinfo.h \
		../opt/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../opt/anaconda3/include/qt/QtGui/qkeysequence.h \
		../opt/anaconda3/include/qt/QtGui/qevent.h \
		../opt/anaconda3/include/qt/QtCore/qvariant.h \
		../opt/anaconda3/include/qt/QtCore/qmap.h \
		../opt/anaconda3/include/qt/QtCore/qdebug.h \
		../opt/anaconda3/include/qt/QtCore/qtextstream.h \
		../opt/anaconda3/include/qt/QtCore/qlocale.h \
		../opt/anaconda3/include/qt/QtCore/qset.h \
		../opt/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../opt/anaconda3/include/qt/QtCore/qurl.h \
		../opt/anaconda3/include/qt/QtCore/qurlquery.h \
		../opt/anaconda3/include/qt/QtCore/qfile.h \
		../opt/anaconda3/include/qt/QtCore/qfiledevice.h \
		../opt/anaconda3/include/qt/QtGui/qvector2d.h \
		../opt/anaconda3/include/qt/QtGui/qtouchdevice.h \
		../opt/anaconda3/include/qt/QtGui/qguiapplication.h \
		../opt/anaconda3/include/qt/QtGui/qinputmethod.h \
		MainWindow.h \
		../opt/anaconda3/include/qt/QtWidgets/QMainWindow \
		../opt/anaconda3/include/qt/QtWidgets/qmainwindow.h \
		../opt/anaconda3/include/qt/QtWidgets/qtabwidget.h \
		../opt/anaconda3/include/qt/QtGui/qicon.h \
		GameBoard.h \
		../opt/anaconda3/include/qt/QtWidgets/QWidget \
		../opt/anaconda3/include/qt/QtWidgets/QGridLayout \
		../opt/anaconda3/include/qt/QtWidgets/qgridlayout.h \
		../opt/anaconda3/include/qt/QtWidgets/qlayout.h \
		../opt/anaconda3/include/qt/QtWidgets/qlayoutitem.h \
		../opt/anaconda3/include/qt/QtWidgets/qboxlayout.h \
		CellButton.h \
		../opt/anaconda3/include/qt/QtWidgets/QPushButton \
		../opt/anaconda3/include/qt/QtWidgets/qpushbutton.h \
		../opt/anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		../opt/anaconda3/include/qt/QtGui/QMouseEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

GameBoard.o: GameBoard.cpp GameBoard.h \
		../opt/anaconda3/include/qt/QtWidgets/QWidget \
		../opt/anaconda3/include/qt/QtWidgets/qwidget.h \
		../opt/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../opt/anaconda3/include/qt/QtGui/qtguiglobal.h \
		../opt/anaconda3/include/qt/QtCore/qglobal.h \
		../opt/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../opt/anaconda3/include/qt/QtCore/qconfig.h \
		../opt/anaconda3/include/qt/QtCore/qtcore-config.h \
		../opt/anaconda3/include/qt/QtCore/qsystemdetection.h \
		../opt/anaconda3/include/qt/QtCore/qprocessordetection.h \
		../opt/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../opt/anaconda3/include/qt/QtCore/qtypeinfo.h \
		../opt/anaconda3/include/qt/QtCore/qsysinfo.h \
		../opt/anaconda3/include/qt/QtCore/qlogging.h \
		../opt/anaconda3/include/qt/QtCore/qflags.h \
		../opt/anaconda3/include/qt/QtCore/qatomic.h \
		../opt/anaconda3/include/qt/QtCore/qbasicatomic.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../opt/anaconda3/include/qt/QtCore/qgenericatomic.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../opt/anaconda3/include/qt/QtCore/qglobalstatic.h \
		../opt/anaconda3/include/qt/QtCore/qmutex.h \
		../opt/anaconda3/include/qt/QtCore/qnumeric.h \
		../opt/anaconda3/include/qt/QtCore/qversiontagging.h \
		../opt/anaconda3/include/qt/QtGui/qtgui-config.h \
		../opt/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../opt/anaconda3/include/qt/QtGui/qwindowdefs.h \
		../opt/anaconda3/include/qt/QtCore/qobjectdefs.h \
		../opt/anaconda3/include/qt/QtCore/qnamespace.h \
		../opt/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../opt/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../opt/anaconda3/include/qt/QtCore/qobject.h \
		../opt/anaconda3/include/qt/QtCore/qstring.h \
		../opt/anaconda3/include/qt/QtCore/qchar.h \
		../opt/anaconda3/include/qt/QtCore/qbytearray.h \
		../opt/anaconda3/include/qt/QtCore/qrefcount.h \
		../opt/anaconda3/include/qt/QtCore/qarraydata.h \
		../opt/anaconda3/include/qt/QtCore/qstringbuilder.h \
		../opt/anaconda3/include/qt/QtCore/qlist.h \
		../opt/anaconda3/include/qt/QtCore/qalgorithms.h \
		../opt/anaconda3/include/qt/QtCore/qiterator.h \
		../opt/anaconda3/include/qt/QtCore/qhashfunctions.h \
		../opt/anaconda3/include/qt/QtCore/qpair.h \
		../opt/anaconda3/include/qt/QtCore/qbytearraylist.h \
		../opt/anaconda3/include/qt/QtCore/qstringlist.h \
		../opt/anaconda3/include/qt/QtCore/qregexp.h \
		../opt/anaconda3/include/qt/QtCore/qstringmatcher.h \
		../opt/anaconda3/include/qt/QtCore/qcoreevent.h \
		../opt/anaconda3/include/qt/QtCore/qscopedpointer.h \
		../opt/anaconda3/include/qt/QtCore/qmetatype.h \
		../opt/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../opt/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../opt/anaconda3/include/qt/QtCore/qobject_impl.h \
		../opt/anaconda3/include/qt/QtCore/qmargins.h \
		../opt/anaconda3/include/qt/QtGui/qpaintdevice.h \
		../opt/anaconda3/include/qt/QtCore/qrect.h \
		../opt/anaconda3/include/qt/QtCore/qsize.h \
		../opt/anaconda3/include/qt/QtCore/qpoint.h \
		../opt/anaconda3/include/qt/QtGui/qpalette.h \
		../opt/anaconda3/include/qt/QtGui/qcolor.h \
		../opt/anaconda3/include/qt/QtGui/qrgb.h \
		../opt/anaconda3/include/qt/QtGui/qrgba64.h \
		../opt/anaconda3/include/qt/QtGui/qbrush.h \
		../opt/anaconda3/include/qt/QtCore/qvector.h \
		../opt/anaconda3/include/qt/QtGui/qmatrix.h \
		../opt/anaconda3/include/qt/QtGui/qpolygon.h \
		../opt/anaconda3/include/qt/QtGui/qregion.h \
		../opt/anaconda3/include/qt/QtCore/qdatastream.h \
		../opt/anaconda3/include/qt/QtCore/qiodevice.h \
		../opt/anaconda3/include/qt/QtCore/qline.h \
		../opt/anaconda3/include/qt/QtGui/qtransform.h \
		../opt/anaconda3/include/qt/QtGui/qpainterpath.h \
		../opt/anaconda3/include/qt/QtGui/qimage.h \
		../opt/anaconda3/include/qt/QtGui/qpixelformat.h \
		../opt/anaconda3/include/qt/QtGui/qpixmap.h \
		../opt/anaconda3/include/qt/QtCore/qsharedpointer.h \
		../opt/anaconda3/include/qt/QtCore/qshareddata.h \
		../opt/anaconda3/include/qt/QtCore/qhash.h \
		../opt/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../opt/anaconda3/include/qt/QtGui/qfont.h \
		../opt/anaconda3/include/qt/QtGui/qfontmetrics.h \
		../opt/anaconda3/include/qt/QtGui/qfontinfo.h \
		../opt/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../opt/anaconda3/include/qt/QtGui/qcursor.h \
		../opt/anaconda3/include/qt/QtGui/qkeysequence.h \
		../opt/anaconda3/include/qt/QtGui/qevent.h \
		../opt/anaconda3/include/qt/QtCore/qvariant.h \
		../opt/anaconda3/include/qt/QtCore/qmap.h \
		../opt/anaconda3/include/qt/QtCore/qdebug.h \
		../opt/anaconda3/include/qt/QtCore/qtextstream.h \
		../opt/anaconda3/include/qt/QtCore/qlocale.h \
		../opt/anaconda3/include/qt/QtCore/qset.h \
		../opt/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../opt/anaconda3/include/qt/QtCore/qurl.h \
		../opt/anaconda3/include/qt/QtCore/qurlquery.h \
		../opt/anaconda3/include/qt/QtCore/qfile.h \
		../opt/anaconda3/include/qt/QtCore/qfiledevice.h \
		../opt/anaconda3/include/qt/QtGui/qvector2d.h \
		../opt/anaconda3/include/qt/QtGui/qtouchdevice.h \
		../opt/anaconda3/include/qt/QtWidgets/QGridLayout \
		../opt/anaconda3/include/qt/QtWidgets/qgridlayout.h \
		../opt/anaconda3/include/qt/QtWidgets/qlayout.h \
		../opt/anaconda3/include/qt/QtWidgets/qlayoutitem.h \
		../opt/anaconda3/include/qt/QtWidgets/qboxlayout.h \
		CellButton.h \
		../opt/anaconda3/include/qt/QtWidgets/QPushButton \
		../opt/anaconda3/include/qt/QtWidgets/qpushbutton.h \
		../opt/anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		../opt/anaconda3/include/qt/QtGui/qicon.h \
		../opt/anaconda3/include/qt/QtGui/QMouseEvent \
		../opt/anaconda3/include/qt/QtGui/QIcon \
		../opt/anaconda3/include/qt/QtCore/QTime \
		../opt/anaconda3/include/qt/QtCore/qdatetime.h \
		../opt/anaconda3/include/qt/QtCore/QCoreApplication \
		../opt/anaconda3/include/qt/QtCore/qcoreapplication.h \
		../opt/anaconda3/include/qt/QtCore/qeventloop.h \
		../opt/anaconda3/include/qt/QtWidgets/QMessageBox \
		../opt/anaconda3/include/qt/QtWidgets/qmessagebox.h \
		../opt/anaconda3/include/qt/QtWidgets/qdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameBoard.o GameBoard.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		../opt/anaconda3/include/qt/QtWidgets/QMainWindow \
		../opt/anaconda3/include/qt/QtWidgets/qmainwindow.h \
		../opt/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../opt/anaconda3/include/qt/QtGui/qtguiglobal.h \
		../opt/anaconda3/include/qt/QtCore/qglobal.h \
		../opt/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../opt/anaconda3/include/qt/QtCore/qconfig.h \
		../opt/anaconda3/include/qt/QtCore/qtcore-config.h \
		../opt/anaconda3/include/qt/QtCore/qsystemdetection.h \
		../opt/anaconda3/include/qt/QtCore/qprocessordetection.h \
		../opt/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../opt/anaconda3/include/qt/QtCore/qtypeinfo.h \
		../opt/anaconda3/include/qt/QtCore/qsysinfo.h \
		../opt/anaconda3/include/qt/QtCore/qlogging.h \
		../opt/anaconda3/include/qt/QtCore/qflags.h \
		../opt/anaconda3/include/qt/QtCore/qatomic.h \
		../opt/anaconda3/include/qt/QtCore/qbasicatomic.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../opt/anaconda3/include/qt/QtCore/qgenericatomic.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../opt/anaconda3/include/qt/QtCore/qglobalstatic.h \
		../opt/anaconda3/include/qt/QtCore/qmutex.h \
		../opt/anaconda3/include/qt/QtCore/qnumeric.h \
		../opt/anaconda3/include/qt/QtCore/qversiontagging.h \
		../opt/anaconda3/include/qt/QtGui/qtgui-config.h \
		../opt/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../opt/anaconda3/include/qt/QtWidgets/qwidget.h \
		../opt/anaconda3/include/qt/QtGui/qwindowdefs.h \
		../opt/anaconda3/include/qt/QtCore/qobjectdefs.h \
		../opt/anaconda3/include/qt/QtCore/qnamespace.h \
		../opt/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../opt/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../opt/anaconda3/include/qt/QtCore/qobject.h \
		../opt/anaconda3/include/qt/QtCore/qstring.h \
		../opt/anaconda3/include/qt/QtCore/qchar.h \
		../opt/anaconda3/include/qt/QtCore/qbytearray.h \
		../opt/anaconda3/include/qt/QtCore/qrefcount.h \
		../opt/anaconda3/include/qt/QtCore/qarraydata.h \
		../opt/anaconda3/include/qt/QtCore/qstringbuilder.h \
		../opt/anaconda3/include/qt/QtCore/qlist.h \
		../opt/anaconda3/include/qt/QtCore/qalgorithms.h \
		../opt/anaconda3/include/qt/QtCore/qiterator.h \
		../opt/anaconda3/include/qt/QtCore/qhashfunctions.h \
		../opt/anaconda3/include/qt/QtCore/qpair.h \
		../opt/anaconda3/include/qt/QtCore/qbytearraylist.h \
		../opt/anaconda3/include/qt/QtCore/qstringlist.h \
		../opt/anaconda3/include/qt/QtCore/qregexp.h \
		../opt/anaconda3/include/qt/QtCore/qstringmatcher.h \
		../opt/anaconda3/include/qt/QtCore/qcoreevent.h \
		../opt/anaconda3/include/qt/QtCore/qscopedpointer.h \
		../opt/anaconda3/include/qt/QtCore/qmetatype.h \
		../opt/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../opt/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../opt/anaconda3/include/qt/QtCore/qobject_impl.h \
		../opt/anaconda3/include/qt/QtCore/qmargins.h \
		../opt/anaconda3/include/qt/QtGui/qpaintdevice.h \
		../opt/anaconda3/include/qt/QtCore/qrect.h \
		../opt/anaconda3/include/qt/QtCore/qsize.h \
		../opt/anaconda3/include/qt/QtCore/qpoint.h \
		../opt/anaconda3/include/qt/QtGui/qpalette.h \
		../opt/anaconda3/include/qt/QtGui/qcolor.h \
		../opt/anaconda3/include/qt/QtGui/qrgb.h \
		../opt/anaconda3/include/qt/QtGui/qrgba64.h \
		../opt/anaconda3/include/qt/QtGui/qbrush.h \
		../opt/anaconda3/include/qt/QtCore/qvector.h \
		../opt/anaconda3/include/qt/QtGui/qmatrix.h \
		../opt/anaconda3/include/qt/QtGui/qpolygon.h \
		../opt/anaconda3/include/qt/QtGui/qregion.h \
		../opt/anaconda3/include/qt/QtCore/qdatastream.h \
		../opt/anaconda3/include/qt/QtCore/qiodevice.h \
		../opt/anaconda3/include/qt/QtCore/qline.h \
		../opt/anaconda3/include/qt/QtGui/qtransform.h \
		../opt/anaconda3/include/qt/QtGui/qpainterpath.h \
		../opt/anaconda3/include/qt/QtGui/qimage.h \
		../opt/anaconda3/include/qt/QtGui/qpixelformat.h \
		../opt/anaconda3/include/qt/QtGui/qpixmap.h \
		../opt/anaconda3/include/qt/QtCore/qsharedpointer.h \
		../opt/anaconda3/include/qt/QtCore/qshareddata.h \
		../opt/anaconda3/include/qt/QtCore/qhash.h \
		../opt/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../opt/anaconda3/include/qt/QtGui/qfont.h \
		../opt/anaconda3/include/qt/QtGui/qfontmetrics.h \
		../opt/anaconda3/include/qt/QtGui/qfontinfo.h \
		../opt/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../opt/anaconda3/include/qt/QtGui/qcursor.h \
		../opt/anaconda3/include/qt/QtGui/qkeysequence.h \
		../opt/anaconda3/include/qt/QtGui/qevent.h \
		../opt/anaconda3/include/qt/QtCore/qvariant.h \
		../opt/anaconda3/include/qt/QtCore/qmap.h \
		../opt/anaconda3/include/qt/QtCore/qdebug.h \
		../opt/anaconda3/include/qt/QtCore/qtextstream.h \
		../opt/anaconda3/include/qt/QtCore/qlocale.h \
		../opt/anaconda3/include/qt/QtCore/qset.h \
		../opt/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../opt/anaconda3/include/qt/QtCore/qurl.h \
		../opt/anaconda3/include/qt/QtCore/qurlquery.h \
		../opt/anaconda3/include/qt/QtCore/qfile.h \
		../opt/anaconda3/include/qt/QtCore/qfiledevice.h \
		../opt/anaconda3/include/qt/QtGui/qvector2d.h \
		../opt/anaconda3/include/qt/QtGui/qtouchdevice.h \
		../opt/anaconda3/include/qt/QtWidgets/qtabwidget.h \
		../opt/anaconda3/include/qt/QtGui/qicon.h \
		GameBoard.h \
		../opt/anaconda3/include/qt/QtWidgets/QWidget \
		../opt/anaconda3/include/qt/QtWidgets/QGridLayout \
		../opt/anaconda3/include/qt/QtWidgets/qgridlayout.h \
		../opt/anaconda3/include/qt/QtWidgets/qlayout.h \
		../opt/anaconda3/include/qt/QtWidgets/qlayoutitem.h \
		../opt/anaconda3/include/qt/QtWidgets/qboxlayout.h \
		CellButton.h \
		../opt/anaconda3/include/qt/QtWidgets/QPushButton \
		../opt/anaconda3/include/qt/QtWidgets/qpushbutton.h \
		../opt/anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		../opt/anaconda3/include/qt/QtGui/QMouseEvent \
		../opt/anaconda3/include/qt/QtWidgets/QMessageBox \
		../opt/anaconda3/include/qt/QtWidgets/qmessagebox.h \
		../opt/anaconda3/include/qt/QtWidgets/qdialog.h \
		../opt/anaconda3/include/qt/QtWidgets/QApplication \
		../opt/anaconda3/include/qt/QtWidgets/qapplication.h \
		../opt/anaconda3/include/qt/QtCore/qcoreapplication.h \
		../opt/anaconda3/include/qt/QtCore/qeventloop.h \
		../opt/anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		../opt/anaconda3/include/qt/QtGui/qguiapplication.h \
		../opt/anaconda3/include/qt/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

CellButton.o: CellButton.cpp CellButton.h \
		../opt/anaconda3/include/qt/QtWidgets/QPushButton \
		../opt/anaconda3/include/qt/QtWidgets/qpushbutton.h \
		../opt/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		../opt/anaconda3/include/qt/QtGui/qtguiglobal.h \
		../opt/anaconda3/include/qt/QtCore/qglobal.h \
		../opt/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		../opt/anaconda3/include/qt/QtCore/qconfig.h \
		../opt/anaconda3/include/qt/QtCore/qtcore-config.h \
		../opt/anaconda3/include/qt/QtCore/qsystemdetection.h \
		../opt/anaconda3/include/qt/QtCore/qprocessordetection.h \
		../opt/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		../opt/anaconda3/include/qt/QtCore/qtypeinfo.h \
		../opt/anaconda3/include/qt/QtCore/qsysinfo.h \
		../opt/anaconda3/include/qt/QtCore/qlogging.h \
		../opt/anaconda3/include/qt/QtCore/qflags.h \
		../opt/anaconda3/include/qt/QtCore/qatomic.h \
		../opt/anaconda3/include/qt/QtCore/qbasicatomic.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		../opt/anaconda3/include/qt/QtCore/qgenericatomic.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		../opt/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		../opt/anaconda3/include/qt/QtCore/qglobalstatic.h \
		../opt/anaconda3/include/qt/QtCore/qmutex.h \
		../opt/anaconda3/include/qt/QtCore/qnumeric.h \
		../opt/anaconda3/include/qt/QtCore/qversiontagging.h \
		../opt/anaconda3/include/qt/QtGui/qtgui-config.h \
		../opt/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		../opt/anaconda3/include/qt/QtWidgets/qabstractbutton.h \
		../opt/anaconda3/include/qt/QtGui/qicon.h \
		../opt/anaconda3/include/qt/QtCore/qsize.h \
		../opt/anaconda3/include/qt/QtCore/qnamespace.h \
		../opt/anaconda3/include/qt/QtCore/qlist.h \
		../opt/anaconda3/include/qt/QtCore/qalgorithms.h \
		../opt/anaconda3/include/qt/QtCore/qiterator.h \
		../opt/anaconda3/include/qt/QtCore/qrefcount.h \
		../opt/anaconda3/include/qt/QtCore/qarraydata.h \
		../opt/anaconda3/include/qt/QtCore/qhashfunctions.h \
		../opt/anaconda3/include/qt/QtCore/qchar.h \
		../opt/anaconda3/include/qt/QtCore/qpair.h \
		../opt/anaconda3/include/qt/QtCore/qbytearraylist.h \
		../opt/anaconda3/include/qt/QtCore/qbytearray.h \
		../opt/anaconda3/include/qt/QtCore/qstring.h \
		../opt/anaconda3/include/qt/QtCore/qstringbuilder.h \
		../opt/anaconda3/include/qt/QtCore/qstringlist.h \
		../opt/anaconda3/include/qt/QtCore/qregexp.h \
		../opt/anaconda3/include/qt/QtCore/qstringmatcher.h \
		../opt/anaconda3/include/qt/QtGui/qpixmap.h \
		../opt/anaconda3/include/qt/QtGui/qpaintdevice.h \
		../opt/anaconda3/include/qt/QtGui/qwindowdefs.h \
		../opt/anaconda3/include/qt/QtCore/qobjectdefs.h \
		../opt/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		../opt/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		../opt/anaconda3/include/qt/QtCore/qrect.h \
		../opt/anaconda3/include/qt/QtCore/qmargins.h \
		../opt/anaconda3/include/qt/QtCore/qpoint.h \
		../opt/anaconda3/include/qt/QtGui/qcolor.h \
		../opt/anaconda3/include/qt/QtGui/qrgb.h \
		../opt/anaconda3/include/qt/QtGui/qrgba64.h \
		../opt/anaconda3/include/qt/QtCore/qsharedpointer.h \
		../opt/anaconda3/include/qt/QtCore/qshareddata.h \
		../opt/anaconda3/include/qt/QtCore/qhash.h \
		../opt/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		../opt/anaconda3/include/qt/QtCore/qobject.h \
		../opt/anaconda3/include/qt/QtCore/qcoreevent.h \
		../opt/anaconda3/include/qt/QtCore/qscopedpointer.h \
		../opt/anaconda3/include/qt/QtCore/qmetatype.h \
		../opt/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		../opt/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		../opt/anaconda3/include/qt/QtCore/qobject_impl.h \
		../opt/anaconda3/include/qt/QtGui/qimage.h \
		../opt/anaconda3/include/qt/QtGui/qpixelformat.h \
		../opt/anaconda3/include/qt/QtGui/qtransform.h \
		../opt/anaconda3/include/qt/QtGui/qmatrix.h \
		../opt/anaconda3/include/qt/QtGui/qpolygon.h \
		../opt/anaconda3/include/qt/QtCore/qvector.h \
		../opt/anaconda3/include/qt/QtGui/qregion.h \
		../opt/anaconda3/include/qt/QtCore/qdatastream.h \
		../opt/anaconda3/include/qt/QtCore/qiodevice.h \
		../opt/anaconda3/include/qt/QtCore/qline.h \
		../opt/anaconda3/include/qt/QtGui/qpainterpath.h \
		../opt/anaconda3/include/qt/QtGui/qkeysequence.h \
		../opt/anaconda3/include/qt/QtWidgets/qwidget.h \
		../opt/anaconda3/include/qt/QtGui/qpalette.h \
		../opt/anaconda3/include/qt/QtGui/qbrush.h \
		../opt/anaconda3/include/qt/QtGui/qfont.h \
		../opt/anaconda3/include/qt/QtGui/qfontmetrics.h \
		../opt/anaconda3/include/qt/QtGui/qfontinfo.h \
		../opt/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		../opt/anaconda3/include/qt/QtGui/qcursor.h \
		../opt/anaconda3/include/qt/QtGui/qevent.h \
		../opt/anaconda3/include/qt/QtCore/qvariant.h \
		../opt/anaconda3/include/qt/QtCore/qmap.h \
		../opt/anaconda3/include/qt/QtCore/qdebug.h \
		../opt/anaconda3/include/qt/QtCore/qtextstream.h \
		../opt/anaconda3/include/qt/QtCore/qlocale.h \
		../opt/anaconda3/include/qt/QtCore/qset.h \
		../opt/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		../opt/anaconda3/include/qt/QtCore/qurl.h \
		../opt/anaconda3/include/qt/QtCore/qurlquery.h \
		../opt/anaconda3/include/qt/QtCore/qfile.h \
		../opt/anaconda3/include/qt/QtCore/qfiledevice.h \
		../opt/anaconda3/include/qt/QtGui/qvector2d.h \
		../opt/anaconda3/include/qt/QtGui/qtouchdevice.h \
		../opt/anaconda3/include/qt/QtGui/QMouseEvent \
		../opt/anaconda3/include/qt/QtGui/QIcon
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CellButton.o CellButton.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_CellButton.o: moc_CellButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CellButton.o moc_CellButton.cpp

moc_GameBoard.o: moc_GameBoard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GameBoard.o moc_GameBoard.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

